config/routes.rb
Rails.application.routes.draw do
  namespace :site do
    get "welcome/index"
  end
  namespace :users_backoffice do
    get "welcome/index"
  end
  namespace :admins_backoffice do
    get "welcome/index" # Dashboard
    resources :admins # Administradores
    resources :subjects # Assuntos/Áreas
    resources :questions # Perguntas
  end
  devise_for :admins
  devise_for :users

  root to: 'site/welcome#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/profile.rb
class Profile < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :subject
  has_many :answers
  accepts_nested_attributes_for :answers, allow_destroy: true
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :questions
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admins_backoffice/admins_controller.rb
class AdminsBackoffice::AdminsController < AdminsBackofficeController
  before_action :verify_password, only: [:update]
  before_action :set_admin, only: [:edit, :update, :destroy]

  def index
    @admins = Admin.all
  end

  def edit
  end

  def new
    @admin = Admin.new
  end

  def create
    @admin = Admin.new(params_admin)
    if @admin.save
      redirect_to admins_backoffice_admins_path, notice: "Administrador cadastrado com sucesso"
    else
      render :new
    end
  end

  def update
    if @admin.update(params_admin)
      redirect_to admins_backoffice_admins_path, notice: "Administrador atualizado com sucesso"
    else
      render :edit
    end
  end

  def destroy
    if @admin.destroy
      redirect_to admins_backoffice_admins_path, notice: "Administrador excluído com sucesso"
    else
      render :index
    end
  end

  private

  def params_admin
    params.require(:admin).permit(:email, :password, :password_confirmation)
  end

  def set_admin
    @admin = Admin.find(params[:id])
  end

  def verify_password
    if params[:admin][:password].blank? && params[:admin][:password_confirmation].blank?
      params[:admin].extract!(:password, :password_confirmation)
    end
  end

end

app/controllers/admins_backoffice/questions_controller.rb
class AdminsBackoffice::QuestionsController < AdminsBackofficeController
  before_action :set_question, only: [:edit, :update, :destroy]
  before_action :get_subjects, only: [:new, :edit]

  def index
    @questions = Question.includes(:subject)
                         .order(:description)
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(params_question)
    if  @question.save
      redirect_to admins_backoffice_questions_path, notice: "Questão cadastrada com sucesso!"
    else
      render :new
    end
  end

  def edit
  end

  def update    
    if  @question.update(params_question)
      redirect_to admins_backoffice_questions_path, notice: "Questão atualizado com sucesso!"
    else
      render :edit
    end
  end

  def destroy
    if  @question.destroy
      redirect_to admins_backoffice_questions_path, notice: "Questão excluída com sucesso!"
    else
      render :index
    end
  end

  private
  
  def params_question
    params.require(:question).permit(:description, :subject_id)
  end

  def set_question
    @question = Question.find(params[:id])
  end

  def get_subjects
    @subjects = Subject.all
  end
end

app/controllers/admins_backoffice/subjects_controller.rb
class AdminsBackoffice::SubjectsController < AdminsBackofficeController
  before_action :set_subject, only: [:edit, :update, :destroy]

  def index
    @subjects = Subject.all.order(:description)
  end

  def edit
  end

  def new
    @subject = Subject.new
  end

  def create
    @subject = Subject.new(params_subject)
    if @subject.save
      redirect_to admins_backoffice_subjects_path, notice: "Assunto/Área cadastrado com sucesso"
    else
      render :new
    end
  end

  def update
    if @subject.update(params_subject)
      redirect_to admins_backoffice_subjects_path, notice: "Assunto/Área atualizado com sucesso"
    else
      render :edit
    end
  end

  def destroy
    if @subject.destroy
      redirect_to admins_backoffice_subjects_path, notice: "Assunto/Área excluído com sucesso"
    else
      render :index
    end
  end

  private

  def params_subject
    params.require(:subject).permit(:description)
  end

  def set_subject
    @subject = Subject.find(params[:id])
  end

end

app/controllers/admins_backoffice/welcome_controller.rb
class AdminsBackoffice::WelcomeController < AdminsBackofficeController
  def index
  end
end

app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
  before_action :authenticate_admin! 
  layout 'admins_backoffice'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/site/welcome_controller.rb
class Site::WelcomeController < SiteController
  def index
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  layout 'site'
end

app/controllers/users_backoffice/welcome_controller.rb
class UsersBackoffice::WelcomeController < UsersBackofficeController
  def index
  end
end

app/controllers/users_backoffice_controller.rb
class UsersBackofficeController < ApplicationController
  before_action :authenticate_user!
  layout 'users_backoffice'
end

app/helpers/admins_backoffice/admins_helper.rb
module AdminsBackoffice::AdminsHelper
end

app/helpers/admins_backoffice/questions_helper.rb
module AdminsBackoffice::QuestionsHelper
end

app/helpers/admins_backoffice/subjects_helper.rb
module AdminsBackoffice::SubjectsHelper
end

app/helpers/admins_backoffice/welcome_helper.rb
module AdminsBackoffice::WelcomeHelper
end

app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper
  def translate_attribute(object = nil, method = nil)
    if object && method
      object.model.human_attribute_name(method)
    else
      "Informe os parâmetros corretamente!"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/site/welcome_helper.rb
module Site::WelcomeHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_backoffice/welcome_helper.rb
module UsersBackoffice::WelcomeHelper
end

app/helpers/users_backoffice_helper.rb
module UsersBackofficeHelper
end

app/views/admins_backoffice/admins/edit.html.erb
<%= render partial: 'admins_backoffice/admins/shared/form',
           locals: { action_message: t('message.editing', model: @admin.model_name.human) } %>

app/views/admins_backoffice/admins/index.html.erb
<!-- Os comandos utilizados foram:  rails g controller AdminsBackoffice::Admins index -->
<%= stylesheet_link_tag "admins_backoffice_admin", "data-turbo-track": "reload" %>

<h1><%= t('message.listing', model: @admins.model_name.human(count: 2)) %></h1>

<hr>

<div class="table_adm">
    <table>
        <thead>
            <tr>
                <th>#</th>
                <th><%= translate_attribute(@admins, :email) %></th>
                <th class="add_admin">
                    <%= link_to new_admins_backoffice_admin_path, class: "table_button_admin" do %>
                        <%= image_tag 'user-plus', size: "25x25" %>
                    <% end %>
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <% @admins.each do |admin| %>
            <tr>
                <td> <%= admin.id %> </td>
                <td> <%= admin.email %> </td>
                <td style="width: 20px;">
                    <%= link_to edit_admins_backoffice_admin_path(admin), class: "table_button_admin" do %>
                        <%= image_tag 'pencil-duotone', size: "25x25" %>
                    <% end %>
                </td>
                <td style="width: 20px;">
                    <%= link_to admins_backoffice_admin_path(admin), method: :delete, class: "table_button_admin", data: { confirm: t('message.confirm_with', item: admin.email ) }  do %>
                        <%= image_tag 'trash-duotone', size: "25x25" %>
                    <% end %>
                </td>
            </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/admins_backoffice/admins/new.html.erb
<%= render partial: 'admins_backoffice/admins/shared/form',
           locals: { action_message: t('message.new', model: @admin.model_name.human) } %>

app/views/admins_backoffice/questions/edit.html.erb
<%= render partial: 'admins_backoffice/questions/shared/form',
           locals: { action_message: t('message.editing', model: @question.model_name.human) } %>

app/views/admins_backoffice/questions/index.html.erb
<!-- Os comandos utilizados foram:  rails g controller AdminsBackoffice::Admins index -->
<%= stylesheet_link_tag "admins_backoffice_admin", "data-turbo-track": "reload" %>

<h1><%= t('message.listing', model: @questions.model_name.human(count: 2)) %></h1>

<hr>

<div class="table_adm">
    <table>
        <thead>
            <tr>
                <th>#</th>
                <th><%= translate_attribute(@questions, :description) %></th>
                <th><%= translate_attribute(@questions, :subject) %></th>
                <th class="add_admin">
                    <%= link_to new_admins_backoffice_question_path, class: "table_button_admin" do %>
                        <%= image_tag 'user-plus', size: "25x25" %>
                    <% end %>
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <% @questions.each do |question| %>
            <tr>
                <td> <%= question.id %> </td>
                <td> <%= question.description.truncate(50) %> </td>
                <td> <%= question.subject.description.truncate(30) %> </td>
                <td style="width: 20px;">
                    <%= link_to edit_admins_backoffice_question_path(question), class: "table_button_admin" do %>
                        <%= image_tag 'pencil-duotone', size: "25x25" %>
                    <% end %>
                </td>
                <td style="width: 20px;">
                    <%= link_to admins_backoffice_question_path(question), method: :delete, class: "table_button_admin", data: { confirm: t('message.confirm_with', item: question.description.truncate(15) ) }  do %>
                        <%= image_tag 'trash-duotone', size: "25x25" %>
                    <% end %>
                </td>
            </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/admins_backoffice/questions/new.html.erb
<%= render partial: 'admins_backoffice/questions/shared/form',
           locals: { action_message: t('message.new', model: @question.model_name.human) } %>

app/views/admins_backoffice/subjects/edit.html.erb
<%= render partial: 'admins_backoffice/subjects/shared/form',
           locals: { action_message: t('message.editing', model: @subject.model_name.human) } %>

app/views/admins_backoffice/subjects/index.html.erb
<!-- Os comandos utilizados foram:  rails g controller AdminsBackoffice::Admins index -->
<%= stylesheet_link_tag "admins_backoffice_admin", "data-turbo-track": "reload" %>

<h1><%= t('message.listing', model: @subjects.model_name.human(count: 2)) %></h1>

<hr>

<div class="table_adm">
    <table>
        <thead>
            <tr>
                <th>#</th>
                <th><%= translate_attribute(@subjects, :description) %></th>
                <th class="add_admin">
                    <%= link_to new_admins_backoffice_subject_path, class: "table_button_admin" do %>
                        <%= image_tag 'user-plus', size: "25x25" %>
                    <% end %>
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <% @subjects.each do |subject| %>
            <tr>
                <td> <%= subject.id %> </td>
                <td> <%= subject.description %> </td>
                <td style="width: 20px;">
                    <%= link_to edit_admins_backoffice_subject_path(subject), class: "table_button_admin" do %>
                        <%= image_tag 'pencil-duotone', size: "25x25" %>
                    <% end %>
                </td>
                <td style="width: 20px;">
                    <%= link_to admins_backoffice_subject_path(subject), method: :delete, class: "table_button_admin", data: { confirm: t('message.confirm_with', item: subject.description) }  do %>
                        <%= image_tag 'trash-duotone', size: "25x25" %>
                    <% end %>
                </td>
            </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/admins_backoffice/subjects/new.html.erb
<%= render partial: 'admins_backoffice/subjects/shared/form',
           locals: { action_message: t('message.new', model: @subject.model_name.human) } %>

app/views/admins_backoffice/welcome/index.html.erb
<h1>Adse::Welcome#index</h1>
<p>Find me in app/views/admins_backoffice/welcome/index.html.erb</p>

app/views/site/welcome/index.html.erb
<h1>Site::Welcome#index</h1>
<p>Find me in app/views/site/welcome/index.html.erb</p>