config/routes.rb
Rails.application.routes.draw do
  namespace :site do
    get "welcome/index"
  end
  namespace :users_backoffice do
    get "welcome/index"
  end
  namespace :admins_backoffice do
    get "welcome/index" # Dashboard
    resources :admins # Administradores
    resources :subjects # Assuntos/Áreas
    resources :questions # Perguntas
  end
  devise_for :admins
  devise_for :users

  root to: 'site/welcome#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/profile.rb
class Profile < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :subject
  has_many :answers
  accepts_nested_attributes_for :answers, allow_destroy: true
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :questions
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
  before_action :authenticate_admin! 
  layout 'admins_backoffice'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/site/welcome_controller.rb
class Site::WelcomeController < SiteController
  def index
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  layout 'site'
end

app/controllers/users_backoffice_controller.rb
class UsersBackofficeController < ApplicationController
  before_action :authenticate_user!
  layout 'users_backoffice'
end

app/helpers/admins_backoffice/admins_helper.rb
module AdminsBackoffice::AdminsHelper
end

app/helpers/admins_backoffice/welcome_helper.rb
module AdminsBackoffice::WelcomeHelper
end

app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper
  def translate_attribute(object = nil, method = nil)
    if object && method
      object.model.human_attribute_name(method)
    else
      "Informe os parâmetros corretamente!"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/site/welcome_helper.rb
module Site::WelcomeHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_backoffice/welcome_helper.rb
module UsersBackoffice::WelcomeHelper
end

app/helpers/users_backoffice_helper.rb
module UsersBackofficeHelper
end

app/views/admins_backoffice/admins/shared/_form.html.erb
<%= stylesheet_link_tag "admins_backoffice_admin", "data-turbo-track": "reload" %>
<h1><%= @admin.model_name.human %></h1>

<hr>

<div class="form_content">
    <%= form_with(model: [ :admins_backoffice, @admin ], local: true) do |form| %>
        <div class="form-group">
            <%= form.label :email %>
            <%= form.text_field :email, class:"form-control", placeholder:t('placeholder.email_adm') %>
        </div>
        <div class="form-group">
            <%= form.label :password %>
            <%= form.password_field :password, class:"form-control", placeholder:t('placeholder.password') %>
        </div>
        <div class="form-group">
            <%= form.label :password_confirmation %>
            <%= form.password_field :password_confirmation, class:"form-control", placeholder:t('placeholder.password_confirmation') %>
        </div>
        
        <button type="submit">
            <%= t('buttons.save') %>
        </button>
    <% end %>
</div>

app/views/layouts/admins_backoffice.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Time To Answer" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "admins_backoffice", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <!-- Nav da página -->
     
    <nav>
      <!-- Botão do DashBoard Admin -->
      <div class="botoes_container">
        <div class="text_adm">
          <p>PAINEL ADM</p>
        </div>
        <%= link_to 'Dashboard', admins_backoffice_welcome_index_path, class: 'botoes_adm' %>
        <%= link_to 'Administradores', admins_backoffice_admins_path, class: 'botoes_adm' %>
        <%= link_to 'Assuntos/Áreas', admins_backoffice_subjects_path, class: 'botoes_adm' %>
        <%= link_to 'Perguntas', admins_backoffice_questions_path, class: 'botoes_adm' %>
      </div>
      <!-- Logout -->
      <div class="logout_adm">
        <%= link_to destroy_admin_session_path, method: :delete do %>
        <%= image_tag 'box-arrow-left.svg' %>
        Sair
        <% end %>
      </div>
    </nav>

    <!-- Content que engloba tudo -->

    <div class="content">
      <header>
        <div class="title-header-adm">
          <h1>Backoffice Administrativo</h1>
        </div>
        <div class="camp-adm">
          <%= current_admin.email %>
          <div class="camp-adm-image"><%= image_tag 'person-circle.svg', size: "25x25" %></div>
        </div>
      </header>
      <main>
        <div class="main-central"><%= yield %></div>
      </main>
    </div>

    <script type="module">
      import Swal from 'sweetalert2'

      <% if notice %>
        Swal.fire({
          icon: 'success',
          title: '<%= j notice %>',
          showConfirmButton: false,
          timer: 2000
        })
      <% end %>

      <% if alert %>
        Swal.fire({
          icon: 'error',
          title: '<%= j alert %>',
          showConfirmButton: false,
          timer: 2000
        })
      <% end %>
    </script>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Time To Answer" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <script type="module">
      import Swal from 'sweetalert2'

      <% if notice %>
        Swal.fire({
          icon: 'success',
          title: '<%= j notice %>',
          showConfirmButton: false,
          timer: 2000
        })
      <% end %>

      <% if alert %>
        Swal.fire({
          icon: 'error',
          title: '<%= j alert %>',
          showConfirmButton: false,
          timer: 2000
        })
      <% end %>
    </script>
  </body>
</html>

app/views/layouts/profiles_backoffice.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Time To Answer" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <h1>LAYOUT PROFILES BACKOFFICE</h1>
    <%= yield %>
  </body>
</html>

app/views/layouts/site.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Time To Answer" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <h1>LAYOUT SITE</h1>
    <%= yield %>
  </body>
</html>

app/views/layouts/users_backoffice.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Time To Answer" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "users_backoffice", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <!-- Nav da página -->
     
    <nav>
      <!-- Botão do DashBoard Admin -->

      <div class="nav_top_container">
        <div class="text_user">
          <p>SCHOOL TEST</p>
        </div>
        <div class="botoes_container">
          <%= link_to 'Dashboard', admins_backoffice_welcome_index_path, class: 'botoes_user' %>
          <%= link_to 'Dashboard', admins_backoffice_welcome_index_path, class: 'botoes_user' %>
          <%= link_to 'Dashboard', admins_backoffice_welcome_index_path, class: 'botoes_user' %>
        </div>
      </div>
      <!-- Logout -->
      <div class="logout_user">
        <%= link_to destroy_user_session_path, method: :delete do %>
        <%= image_tag 'box-arrow-left.svg' %>
        Sair
        <% end %>
      </div>
    </nav>

    <!-- Content que engloba tudo -->

    <div class="content">
      <header>
        <div class="title-header-user">
          <h1>Painel do Usuário</h1>
        </div>
        <div class="camp-user">
          <%= current_user.email %>
          <div class="camp-user-image"><%= image_tag 'person-circle.svg', size: "25x25" %></div>
        </div>
      </header>
      <main>
        <div class="main-central"><%= yield %></div>
      </main>
    </div>
  </body>
</html>